// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrangepuffPortal.ConfigData.Infrastructure;

#nullable disable

namespace OrangepuffPortal.ConfigData.Infrastructure.Migrations
{
    [DbContext(typeof(ConfigDataDbContext))]
    [Migration("20260819033231_InitPostgres")]
    partial class InitPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("configdata")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrangepuffPortal.ConfigData.Domain.Entity.ConfigDataEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("iId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AllowEditByScreen")
                        .HasColumnType("boolean")
                        .HasColumnName("bAllowEditByScreen");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("sDescription");

                    b.Property<DateTime?>("InsertedTime")
                        .HasColumnType("timestamp")
                        .HasColumnName("dtInsertedTime");

                    b.Property<int?>("InsertedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("iInsertedUserId");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sKey");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("timestamp")
                        .HasColumnName("dtUpdatedTime");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("iUpdatedUserId");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("sValue");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("UQ_ConfigData_Key");

                    b.ToTable("ConfigData", "configdata");
                });
#pragma warning restore 612, 618
        }
    }
}
