// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OCRWeb.Identity.Infrastructure;

#nullable disable

namespace OCRWeb.Identity.Infrastructure.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20260718022208_AddExternalLogins")]
    partial class AddExternalLogins
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OCRWeb.Identity.Domain.Entity.ExternalLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("InsertedTime")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("dtInsertedTime");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sProvider");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("sProviderKey");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("iUserId");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ProviderKey")
                        .IsUnique()
                        .HasDatabaseName("UQ_ExternalLogins_Provider_ProviderKey");

                    b.HasIndex("UserId", "Provider")
                        .IsUnique()
                        .HasDatabaseName("UQ_ExternalLogins_UserId_Provider");

                    b.ToTable("ExternalLogins", "identity");
                });

            modelBuilder.Entity("OCRWeb.Identity.Domain.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("sDisplayName");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("sEmail");

                    b.Property<DateTime>("InsertedTime")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("dtInsertedTime");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("btIsActive");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("sPasswordHash");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("dtUpdatedTime");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sUsername");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("UQ_Users_Username");

                    b.ToTable("Users", "identity");
                });

            modelBuilder.Entity("OCRWeb.Identity.Domain.Entity.ExternalLogin", b =>
                {
                    b.HasOne("OCRWeb.Identity.Domain.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
