// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrangepuffPortal.Theme.Infrastructure;

#nullable disable

namespace OrangepuffPortal.Theme.Infrastructure.Migrations
{
    [DbContext(typeof(ThemeDbContext))]
    [Migration("20260819033248_InitPostgres")]
    partial class InitPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("portal")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrangepuffPortal.Theme.Domain.Entity.Theme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("iId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("sDescription");

                    b.Property<DateTime>("InsertedTime")
                        .HasColumnType("timestamp(3)")
                        .HasColumnName("dtInsertedTime");

                    b.Property<int?>("InsertedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("iInsertedUserId");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("btActive");

                    b.Property<string>("ThemeCode")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sThemeCode");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("timestamp(3)")
                        .HasColumnName("dtUpdatedTime");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("iUpdatedUserId");

                    b.HasKey("Id");

                    b.HasIndex("ThemeCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_Themes_ThemeCode");

                    b.ToTable("Themes", "portal");
                });

            modelBuilder.Entity("OrangepuffPortal.Theme.Domain.Entity.ThemeDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("iId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AllowedValues")
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("sAllowedValues");

                    b.Property<DateTime>("InsertedTime")
                        .HasColumnType("timestamp(3)")
                        .HasColumnName("dtInsertedTime");

                    b.Property<int?>("InsertedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("iInsertedUserId");

                    b.Property<string>("PropertyDescription")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("sPropertyDescription");

                    b.Property<string>("PropertyKey")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sPropertyKey");

                    b.Property<string>("PropertyLabel")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("sPropertyLabel");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("sPropertyType");

                    b.Property<string>("PropertyValue")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("sPropertyValue");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("iSortOrder");

                    b.Property<int>("ThemeElementId")
                        .HasColumnType("integer")
                        .HasColumnName("iThemeElementId");

                    b.Property<string>("Unit")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sUnit");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("timestamp(3)")
                        .HasColumnName("dtUpdatedTime");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("iUpdatedUserId");

                    b.HasKey("Id");

                    b.HasIndex("ThemeElementId", "PropertyKey")
                        .IsUnique()
                        .HasDatabaseName("UQ_ThemeDetails_ElementId_PropertyKey");

                    b.ToTable("ThemeDetails", "portal");
                });

            modelBuilder.Entity("OrangepuffPortal.Theme.Domain.Entity.ThemeElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("iId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("sDescription");

                    b.Property<string>("ElementCode")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sElementCode");

                    b.Property<DateTime>("InsertedTime")
                        .HasColumnType("timestamp(3)")
                        .HasColumnName("dtInsertedTime");

                    b.Property<int?>("InsertedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("iInsertedUserId");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("iSortOrder");

                    b.Property<int>("ThemeSectionId")
                        .HasColumnType("integer")
                        .HasColumnName("iThemeSectionId");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("timestamp(3)")
                        .HasColumnName("dtUpdatedTime");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("iUpdatedUserId");

                    b.HasKey("Id");

                    b.HasIndex("ThemeSectionId", "ElementCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_ThemeElements_SectionId_ElementCode");

                    b.ToTable("ThemeElements", "portal");
                });

            modelBuilder.Entity("OrangepuffPortal.Theme.Domain.Entity.ThemeSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("iId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("sDescription");

                    b.Property<DateTime>("InsertedTime")
                        .HasColumnType("timestamp(3)")
                        .HasColumnName("dtInsertedTime");

                    b.Property<int?>("InsertedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("iInsertedUserId");

                    b.Property<string>("SectionCode")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sSectionCode");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("iSortOrder");

                    b.Property<int>("ThemeId")
                        .HasColumnType("integer")
                        .HasColumnName("iThemeId");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("timestamp(3)")
                        .HasColumnName("dtUpdatedTime");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("iUpdatedUserId");

                    b.HasKey("Id");

                    b.HasIndex("ThemeId", "SectionCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_ThemeSections_ThemeId_SectionCode");

                    b.ToTable("ThemeSections", "portal");
                });

            modelBuilder.Entity("OrangepuffPortal.Theme.Domain.Entity.ThemeDetail", b =>
                {
                    b.HasOne("OrangepuffPortal.Theme.Domain.Entity.ThemeElement", null)
                        .WithMany()
                        .HasForeignKey("ThemeElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrangepuffPortal.Theme.Domain.Entity.ThemeElement", b =>
                {
                    b.HasOne("OrangepuffPortal.Theme.Domain.Entity.ThemeSection", null)
                        .WithMany()
                        .HasForeignKey("ThemeSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrangepuffPortal.Theme.Domain.Entity.ThemeSection", b =>
                {
                    b.HasOne("OrangepuffPortal.Theme.Domain.Entity.Theme", null)
                        .WithMany()
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
