// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OCRWeb.ProjectManagement.Infrastructure;

#nullable disable

namespace OCRWeb.ProjectManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20260819082024_RenameProjectPkToIId")]
    partial class RenameProjectPkToIId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("project")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OCRWeb.ProjectManagement.Domain.Entity.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("iId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("InsertedTime")
                        .HasColumnType("timestamp(3)")
                        .HasColumnName("dtInsertedTime");

                    b.Property<int>("InsertedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("iInsertedUserId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("sName");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("timestamp(3)")
                        .HasColumnName("dtUpdatedTime");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("iUpdatedUserId");

                    b.HasKey("Id");

                    b.ToTable("Projects", "project");
                });
#pragma warning restore 612, 618
        }
    }
}
