// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OCRWeb.ProjectManagement.Infrastructure;

#nullable disable

namespace OCRWeb.ProjectManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20260725041524_InitialProjectManagement")]
    partial class InitialProjectManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("project")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OCRWeb.ProjectManagement.Domain.Entity.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("InsertedTime")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("dtInsertedTime");

                    b.Property<int>("InsertedUserId")
                        .HasColumnType("int")
                        .HasColumnName("iInsertedUserId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("sName");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("dtUpdatedTime");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnName("iUpdatedUserId");

                    b.HasKey("Id");

                    b.ToTable("Projects", "project");
                });
#pragma warning restore 612, 618
        }
    }
}
