-- Reference schema for the security-rule permission model.
-- Generated by EF Core migration 20260719061336_AddSecurityRules; kept here as a plain-SQL
-- reference alongside security-rules-permission-design.md. The migration itself is the
-- source of truth — regenerate this file by hand if the shape drifts.

ALTER TABLE [identity].[Users] ADD
    [btIsTemplateUser] [bit] NOT NULL CONSTRAINT [DF_Users_btIsTemplateUser] DEFAULT (0),
    [iParentId] [int] NULL;
GO

ALTER TABLE [identity].[Users] ADD CONSTRAINT [FK_Users_Users_iParentId]
    FOREIGN KEY ([iParentId]) REFERENCES [identity].[Users] ([iId]) ON DELETE NO ACTION;
GO

CREATE INDEX [IX_Users_iParentId] ON [identity].[Users] ([iParentId]);
GO

CREATE TABLE [identity].[SecurityRuleCategory] (
    [iId] [int] IDENTITY(1,1) NOT NULL,
    [sCategoryDesc] [nvarchar](100) NOT NULL,
    [sTextCode] [nvarchar](60) NULL,
    [btHidden] [bit] NOT NULL CONSTRAINT [DF_SecurityRuleCategory_btHidden] DEFAULT (0),
    [iInsertedUserId] [int] NOT NULL,
    [dtInsertedTime] [datetime2](3) NOT NULL,
    [iUpdatedUserId] [int] NULL,
    [dtUpdatedTime] [datetime2](3) NULL,
    CONSTRAINT [PK_SecurityRuleCategory] PRIMARY KEY CLUSTERED ([iId] ASC)
);
GO

CREATE UNIQUE INDEX [UQ_SecurityRuleCategory_CategoryDesc] ON [identity].[SecurityRuleCategory] ([sCategoryDesc]);
GO

CREATE TABLE [identity].[SecurityRuleItems] (
    [iId] [int] IDENTITY(1,1) NOT NULL,
    [iRuleCategoryId] [int] NOT NULL,
    [sSecurityRuleCode] [nvarchar](100) NOT NULL,
    [sSecurityRuleDesc] [nvarchar](255) NOT NULL,
    [iRuleType] [int] NOT NULL, -- 0=Boolean, 1=Integer, 2=Decimal
    [iSortOrder] [int] NULL,
    [sTextCode] [nvarchar](90) NULL,
    [btHidden] [bit] NOT NULL CONSTRAINT [DF_SecurityRuleItems_btHidden] DEFAULT (0),
    [iInsertedUserId] [int] NOT NULL,
    [dtInsertedTime] [datetime2](3) NOT NULL,
    [iUpdatedUserId] [int] NULL,
    [dtUpdatedTime] [datetime2](3) NULL,
    CONSTRAINT [PK_SecurityRuleItems] PRIMARY KEY CLUSTERED ([iId] ASC),
    CONSTRAINT [FK_SecurityRuleItems_SecurityRuleCategory_iRuleCategoryId]
        FOREIGN KEY ([iRuleCategoryId]) REFERENCES [identity].[SecurityRuleCategory] ([iId]) ON DELETE NO ACTION
);
GO

CREATE UNIQUE INDEX [UQ_SecurityRuleItems_Code] ON [identity].[SecurityRuleItems] ([sSecurityRuleCode]);
CREATE INDEX [IX_SecurityRuleItems_iRuleCategoryId] ON [identity].[SecurityRuleItems] ([iRuleCategoryId]);
GO

CREATE TABLE [identity].[SecurityUserRuleItems] (
    [iId] [int] IDENTITY(1,1) NOT NULL,
    [iUserId] [int] NOT NULL,
    [iRuleItemId] [int] NOT NULL,
    [iAllowed] [int] NULL,        -- 0/1 flag when RuleType=Boolean; limit value when RuleType=Integer
    [nAllowed] [numeric](10, 2) NULL, -- limit value when RuleType=Decimal
    [iInsertedUserId] [int] NOT NULL,
    [dtInsertedTime] [datetime2](3) NOT NULL,
    [iUpdatedUserId] [int] NULL,
    [dtUpdatedTime] [datetime2](3) NULL,
    CONSTRAINT [PK_SecurityUserRuleItems] PRIMARY KEY CLUSTERED ([iId] ASC),
    CONSTRAINT [FK_SecurityUserRuleItems_Users_iUserId]
        FOREIGN KEY ([iUserId]) REFERENCES [identity].[Users] ([iId]) ON DELETE CASCADE,
    CONSTRAINT [FK_SecurityUserRuleItems_SecurityRuleItems_iRuleItemId]
        FOREIGN KEY ([iRuleItemId]) REFERENCES [identity].[SecurityRuleItems] ([iId]) ON DELETE NO ACTION
);
GO

CREATE UNIQUE INDEX [UQ_SecurityUserRuleItems_UserId_RuleItemId] ON [identity].[SecurityUserRuleItems] ([iUserId], [iRuleItemId]);
CREATE INDEX [IX_SecurityUserRuleItems_iRuleItemId] ON [identity].[SecurityUserRuleItems] ([iRuleItemId]);
GO
