// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OCRWeb.DocumentProcessing.Infrastructure;

#nullable disable

namespace OCRWeb.DocumentProcessing.Infrastructure.Migrations
{
    [DbContext(typeof(DocumentProcessingDbContext))]
    partial class DocumentProcessingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("docproc")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OCRWeb.DocumentProcessing.Domain.Entity.PdfFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<byte[]>("Checksum")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)")
                        .HasColumnName("binChecksum");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sContentType");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sFileName");

                    b.Property<int>("FileType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("iFileType");

                    b.Property<DateTime>("InsertedTime")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("dtInsertedTime");

                    b.Property<int>("InsertedUserId")
                        .HasColumnType("int")
                        .HasColumnName("iInsertedUserId");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProjectId");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("biSizeBytes");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("dtUpdatedTime");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnName("iUpdatedUserId");

                    b.HasKey("Id");

                    b.ToTable("PDFFiles", "docproc");
                });

            modelBuilder.Entity("OCRWeb.DocumentProcessing.Domain.Entity.PdfFileContent", b =>
                {
                    b.Property<Guid>("PdfFileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PdfFileId");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("binContent");

                    b.Property<DateTime>("InsertedTime")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("dtInsertedTime");

                    b.Property<int>("InsertedUserId")
                        .HasColumnType("int")
                        .HasColumnName("iInsertedUserId");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("dtUpdatedTime");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int")
                        .HasColumnName("iUpdatedUserId");

                    b.HasKey("PdfFileId");

                    b.ToTable("PDFFileContents", "docproc");
                });

            modelBuilder.Entity("OCRWeb.DocumentProcessing.Domain.Entity.PdfFile", b =>
                {
                    b.OwnsOne("OCRWeb.DocumentProcessing.Domain.ValueObjects.FileProperties", "Properties", b1 =>
                        {
                            b1.Property<Guid>("PdfFileId");

                            b1.Property<int>("CropX");

                            b1.Property<int>("CropY");

                            b1.Property<int>("Height");

                            b1.Property<int>("PageNo");

                            b1.Property<int>("Width");

                            b1.HasKey("PdfFileId");

                            b1.ToTable("PDFFiles", "docproc");

                            b1
                                .ToJson("sFileProperties")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("PdfFileId");
                        });

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("OCRWeb.DocumentProcessing.Domain.Entity.PdfFileContent", b =>
                {
                    b.HasOne("OCRWeb.DocumentProcessing.Domain.Entity.PdfFile", null)
                        .WithOne("Content")
                        .HasForeignKey("OCRWeb.DocumentProcessing.Domain.Entity.PdfFileContent", "PdfFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OCRWeb.DocumentProcessing.Domain.Entity.PdfFile", b =>
                {
                    b.Navigation("Content")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
