// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrangepuffPortal.Config.Infrastructure;

#nullable disable

namespace OrangepuffPortal.Config.Infrastructure.Migrations
{
    [DbContext(typeof(ConfigDbContext))]
    [Migration("20260819033223_InitPostgres")]
    partial class InitPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("config")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrangepuffPortal.Config.Domain.Entity.ConfigItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("iId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowUserEdit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("btAllowUserEdit");

                    b.Property<string>("ConfigCode")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("sConfigCode");

                    b.Property<string>("ConfigName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("sConfigName");

                    b.Property<int>("ConfigType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("iConfigType");

                    b.Property<bool?>("DefaultBoolValue")
                        .HasColumnType("boolean")
                        .HasColumnName("btDefaultValue");

                    b.Property<decimal?>("DefaultDecimalValue")
                        .HasColumnType("decimal(8,3)")
                        .HasColumnName("nDefaultValue");

                    b.Property<int?>("DefaultIntValue")
                        .HasColumnType("integer")
                        .HasColumnName("iDefaultValue");

                    b.Property<string>("DefaultStringValue")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("sDefaultValue");

                    b.Property<DateTime?>("InsertedTime")
                        .HasColumnType("timestamp")
                        .HasColumnName("dtInsertedTime");

                    b.Property<int?>("InsertedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("iInsertedUserId");

                    b.Property<int>("SectionId")
                        .HasColumnType("integer")
                        .HasColumnName("iSectionId");

                    b.Property<bool>("Show")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("btShow");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("iSortOrder");

                    b.Property<string>("TextCode")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sTextCode");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("timestamp")
                        .HasColumnName("dtUpdatedTime");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("iUpdatedUserId");

                    b.HasKey("Id");

                    b.HasIndex("ConfigCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_Configs_ConfigCode");

                    b.HasIndex("SectionId");

                    b.ToTable("Configs", "config");
                });

            modelBuilder.Entity("OrangepuffPortal.Config.Domain.Entity.ConfigSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("iId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("InsertedTime")
                        .HasColumnType("timestamp")
                        .HasColumnName("dtInsertedTime");

                    b.Property<int?>("InsertedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("iInsertedUserId");

                    b.Property<string>("SectionDesc")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("sSectionDesc");

                    b.Property<bool>("Show")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("btShow");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("iSortOrder");

                    b.Property<string>("TextCode")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sTextCode");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("timestamp")
                        .HasColumnName("dtUpdatedTime");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("iUpdatedUserId");

                    b.HasKey("Id");

                    b.HasIndex("TextCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_ConfigSections_TextCode");

                    b.ToTable("ConfigSections", "config");
                });

            modelBuilder.Entity("OrangepuffPortal.Config.Domain.Entity.ConfigUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("iId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("btActive");

                    b.Property<bool?>("BoolValue")
                        .HasColumnType("boolean")
                        .HasColumnName("btConfigValue");

                    b.Property<int>("ConfigId")
                        .HasColumnType("integer")
                        .HasColumnName("iConfigId");

                    b.Property<decimal?>("DecimalValue")
                        .HasColumnType("decimal(8,3)")
                        .HasColumnName("nConfigValue");

                    b.Property<DateTime>("InsertedTime")
                        .HasColumnType("timestamp")
                        .HasColumnName("dtInsertedTime");

                    b.Property<int>("InsertedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("iInsertedUserId");

                    b.Property<int?>("IntValue")
                        .HasColumnType("integer")
                        .HasColumnName("iConfigValue");

                    b.Property<string>("StringValue")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("sConfigValue");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("timestamp")
                        .HasColumnName("dtUpdatedTime");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("iUpdatedUserId");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("iUserId");

                    b.HasKey("Id");

                    b.HasIndex("ConfigId");

                    b.HasIndex("UserId", "ConfigId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ConfigUsers_User_Config");

                    b.ToTable("ConfigUsers", "config");
                });

            modelBuilder.Entity("OrangepuffPortal.Config.Domain.Entity.ConfigUserHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("iId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("btActive");

                    b.Property<bool?>("BoolValue")
                        .HasColumnType("boolean")
                        .HasColumnName("btConfigValue");

                    b.Property<int>("ConfigId")
                        .HasColumnType("integer")
                        .HasColumnName("iConfigId");

                    b.Property<int>("ConfigUserId")
                        .HasColumnType("integer")
                        .HasColumnName("iConfigUserId");

                    b.Property<decimal?>("DecimalValue")
                        .HasColumnType("decimal(8,3)")
                        .HasColumnName("nConfigValue");

                    b.Property<DateTime>("InsertedTime")
                        .HasColumnType("timestamp")
                        .HasColumnName("dtInsertedTime");

                    b.Property<int>("InsertedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("iInsertedUserId");

                    b.Property<int?>("IntValue")
                        .HasColumnType("integer")
                        .HasColumnName("iConfigValue");

                    b.Property<string>("StringValue")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("sConfigValue");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("timestamp")
                        .HasColumnName("dtUpdatedTime");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("iUpdatedUserId");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("iUserId");

                    b.HasKey("Id");

                    b.HasIndex("ConfigUserId")
                        .HasDatabaseName("IX_ConfigUsersHistory_ConfigUserId");

                    b.ToTable("ConfigUsersHistory", "config");
                });

            modelBuilder.Entity("OrangepuffPortal.Config.Domain.Entity.ConfigItem", b =>
                {
                    b.HasOne("OrangepuffPortal.Config.Domain.Entity.ConfigSection", null)
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OrangepuffPortal.Config.Domain.Entity.ConfigUser", b =>
                {
                    b.HasOne("OrangepuffPortal.Config.Domain.Entity.ConfigItem", null)
                        .WithMany()
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OrangepuffPortal.Config.Domain.Entity.ConfigUserHistory", b =>
                {
                    b.HasOne("OrangepuffPortal.Config.Domain.Entity.ConfigUser", null)
                        .WithMany()
                        .HasForeignKey("ConfigUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
