// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OCRWeb.Document.Infrastructure;

#nullable disable

namespace OCRWeb.Document.Infrastructure.Migrations
{
    [DbContext(typeof(DocumentDbContext))]
    partial class DocumentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("docproc")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OCRWeb.Document.Domain.Entity.PdfFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("iId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Checksum")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("binChecksum");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sContentType");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sFileName");

                    b.Property<int>("FileType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("iFileType");

                    b.Property<DateTime>("InsertedTime")
                        .HasColumnType("timestamp(3)")
                        .HasColumnName("dtInsertedTime");

                    b.Property<int>("InsertedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("iInsertedUserId");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("btActive");

                    b.Property<int>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("iParentId");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("biSizeBytes");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("timestamp(3)")
                        .HasColumnName("dtUpdatedTime");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("iUpdatedUserId");

                    b.HasKey("Id");

                    b.ToTable("Files", "docproc");
                });

            modelBuilder.Entity("OCRWeb.Document.Domain.Entity.PdfFileContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("iId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("binContent");

                    b.Property<int>("FileId")
                        .HasColumnType("integer")
                        .HasColumnName("iFileId");

                    b.Property<DateTime>("InsertedTime")
                        .HasColumnType("timestamp(3)")
                        .HasColumnName("dtInsertedTime");

                    b.Property<int>("InsertedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("iInsertedUserId");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("timestamp(3)")
                        .HasColumnName("dtUpdatedTime");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("iUpdatedUserId");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.ToTable("FileContents", "docproc");
                });

            modelBuilder.Entity("OCRWeb.Document.Domain.Entity.PdfFile", b =>
                {
                    b.OwnsOne("OCRWeb.Document.Domain.ValueObjects.FileProperties", "Properties", b1 =>
                        {
                            b1.Property<int>("PdfFileId");

                            b1.Property<int>("CropX");

                            b1.Property<int>("CropY");

                            b1.Property<int>("Height");

                            b1.Property<int>("PageNo");

                            b1.Property<int>("Width");

                            b1.HasKey("PdfFileId");

                            b1.ToTable("Files", "docproc");

                            b1
                                .ToJson("sFileProperties")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PdfFileId");
                        });

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("OCRWeb.Document.Domain.Entity.PdfFileContent", b =>
                {
                    b.HasOne("OCRWeb.Document.Domain.Entity.PdfFile", null)
                        .WithOne("Content")
                        .HasForeignKey("OCRWeb.Document.Domain.Entity.PdfFileContent", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OCRWeb.Document.Domain.Entity.PdfFile", b =>
                {
                    b.Navigation("Content")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
